Repository ubsuny/CP1-24-HW4, pull requests merged in 2024-11, with the labels that each got.

#16 Added raw data files and documentation on method for grouping
  Data/data_plotter.ipynb
  Data/raw_data_table1.md
  Data/raw_data_table1_grouped.md
  Data/raw_data_table2.md
  Documentation/group_selection.md
  Documentation/reproduced_figure1.png
Labels: documentation

#34 Selection of Nine groups.md
  Documentation.md
Labels: documentation

#28 Unit Testing for linear_fit.py and edits to python to make it pylint compliant.
  pseudo_code/linear_fit.py
  pseudo_code/test_linear_fit.py
  pseudo_code/test_placeholder.csv
Labels: enhancement, python

#43 Fitting parameters
  fit_param.py
  test_fit_param.py
Labels: python

#49 changed path of PR template to be recognized by github
  docs/pull_request_template.md
Labels: bug

#31 Grouped the data of 22 Nebulae and generated the csv file
  code_generate_csv_file.py
  hubble_9_grouping.csv
  hubble_table1_9_groups_sorted.csv
Labels: documentation, python

#42 Added code to read data from csv file
  Least-squares Fit/fit_and_plot.py
  Least-squares Fit/test_import_csv.py
Labels: enhancement

#37 estimating the age of the universe
  age_of_univ/age_of_un_funk.py
Labels: python
