Repository ubsuny/CP1-24-HW4, pull requests merged in 2024-10, with the labels that each got.

#5 Added our standard python devcontainer
  .devcontainer/python/devcontainer.json
Labels: enhancement

#13 Pseudo-code
  pseudo_code/linear_fit.py
Labels: python

#17 Cython Module
  .gitignore
  cython/code/Example.ipynb
  cython/code/compute.c
  cython/code/compute.pyx
  cython/code/profiler.py
  cython/code/setup.py
  cython/docs/compute.html
  cython/docs/cython-tips-shortlist.md
  cython/docs/how-to-run.md
  cython/docs/profiling_results.txt
Labels: enhancement, python, C++

#21 Created a requirements text file with useable libaries.
  requirements.txt
Labels: todo

#24 Modified the workflows files
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: enhancement, Organization

#25 Created a Pull Request Template
  PullRequestTemplate.md
Labels: documentation, Organization

#39 Modifying the linting workflows to clear the cache
  .github/workflows/lint.yml
Labels: bug, enhancement, Organization

#32 Least-squares Fit
  Least-squares Fit/fit_and_plot.py
  Least-squares Fit/grouped_data_filtered.csv
  Least-squares Fit/grouped_data_generator.py
  Least-squares Fit/how_to_run.ipynb
  Least-squares Fit/linear_fit.py
  Least-squares Fit/raw_data_table1_grouped.md
Labels: documentation, enhancement, python
